root = "."
tmp_dir = "tmp"

[build]
cmd = "cd be/api && go build -o ../../tmp/app"
bin = "tmp/app"
full_bin = "PORT=$PORT ./tmp/app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true

[screen]
clear_on_rebuild = true
